FROM centos:7
RUN set -euxo pipefail && \
    yum install -y bash java-1.8.0-openjdk-headless.x86_64 less && \
    yum clean all

WORKDIR /

COPY files/presto-cli-${PRESTO_VERSION}-executable.jar /usr/bin/presto

ENTRYPOINT ["/usr/bin/presto"]