FROM openjdk:8-slim

ENV PRESTO_VERSION 0.217
ENV PRESTO_HOME=/usr/local/presto
ENV BASE_URL=https://repo1.maven.org/maven2

# install dev tools
RUN apt-get update
RUN apt-get install -y curl tar sudo wget
#RUN pip install jinja2

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin

WORKDIR /usr/local
RUN wget -q https://repo1.maven.org/maven2/com/facebook/presto/presto-server/${PRESTO_VERSION}/presto-server-${PRESTO_VERSION}.tar.gz
RUN tar xvzf presto-server-${PRESTO_VERSION}.tar.gz -C /usr/local/
#RUN ln -s /usr/local/presto-server-${PRESTO_VERSION} $PRESTO_HOME
RUN cp -r /usr/local/presto-server-${PRESTO_VERSION} $PRESTO_HOME
RUN rm /usr/local/presto-server-${PRESTO_VERSION}.tar.gz

# Create data dir
RUN mkdir -p $PRESTO_HOME/data
VOLUME ["$PRESTO_HOME/data"]